name: deploy-payments

on:
  push:
    branches:
      - master
    paths:
      - 'payments/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && docker build -t 19daveb68/payments .
      - run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PW }}
      - run: docker push 19daveb68/payments
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}
      - run: doctl kubernetes cluster kubeconfig save gittix-db1
      - run: kubectl rollout restart deployment payments-depl
